# CMake generated Testfile for 
# Source directory: C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1
# Build directory: C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[closure_native_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/Debug/gambit_tests.exe" "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/assets/micro_xy.gblut")
  set_tests_properties([=[closure_native_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;25;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[closure_native_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/Release/gambit_tests.exe" "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/assets/micro_xy.gblut")
  set_tests_properties([=[closure_native_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;25;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[closure_native_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/MinSizeRel/gambit_tests.exe" "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/assets/micro_xy.gblut")
  set_tests_properties([=[closure_native_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;25;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[closure_native_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/RelWithDebInfo/gambit_tests.exe" "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/assets/micro_xy.gblut")
  set_tests_properties([=[closure_native_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;25;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
else()
  add_test([=[closure_native_contract]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[closure_cuda_error_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/Debug/gambit_cuda_contract.exe")
  set_tests_properties([=[closure_cuda_error_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;44;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[closure_cuda_error_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/Release/gambit_cuda_contract.exe")
  set_tests_properties([=[closure_cuda_error_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;44;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[closure_cuda_error_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/MinSizeRel/gambit_cuda_contract.exe")
  set_tests_properties([=[closure_cuda_error_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;44;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[closure_cuda_error_contract]=] "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/validation/full/cuda_build/RelWithDebInfo/gambit_cuda_contract.exe")
  set_tests_properties([=[closure_cuda_error_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;44;add_test;C:/RUUDDENDAASKOANAL/Gambit_Closure_4.0.1/CMakeLists.txt;0;")
else()
  add_test([=[closure_cuda_error_contract]=] NOT_AVAILABLE)
endif()
